<?php
    require("Controler/verifSession.php");
?>
<?php
    require("View/AjoutNote/headerAjoutNote.php");
?>
    <br><br>
        <?php
            require("View/AjoutNote/formAjoutNote.php");
        ?>
    <br>
<?php
    require("View/Connexion/footerConnexion.php");
?>
